<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Bootstrap setting options with subtheme ones.
 */
function bootstrap_sass_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_navbar_top_background']['#options'] = array(
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  );
  $form['components']['navbar']['bootstrap_navbar_background']['#options'] = array(
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  );
}

function bootstrap_sass_preprocess_menu_local_tasks(&$variables) {
  // Only run on node pages.
  $route_match = \Drupal::routeMatch();
  $node = $route_match->getParameter('node');
  if ($node && is_object($node) && method_exists($node, 'bundle')) {
    $hide_bundles = [
      'personal_information',
      'education',
      'employment_details',
      'referee',
      'additional_information',
      'file_upload',
    ];
    if (in_array($node->bundle(), $hide_bundles, TRUE)) {
      // Remove all tabs (primary tasks).
      $variables['primary'] = [];
      // Optionally, also remove secondary tabs:
      $variables['secondary'] = [];
    }
  }
}